title = "Cub Scouts Pack499"
baseURL = "https://www.sbiapack499.org"
languageCode = "en-us"
theme = 'ananke'
resourceDir = "../resources"
featured_image =  '/images/scouts-bsa-pack499.jpeg'


#DefaultContentLanguage = "en"
#SectionPagesMenu = "main"
Paginate = 12 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
#enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = "black"
  author = "Cubmaster"
  favicon = "https://www.scouting.org/wp-content/uploads/2022/06/cubscouts.png"
  site_logo = "https://www.scouting.org/wp-content/uploads/2022/06/cubscouts.png"
  featured_image =  '/images/scouts-bsa-pack499.jpeg'
  description = "BSA Cub scouting with Pack499 @SBIA"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-blue"
  recent_posts_number = 8

[[params.ananke_socials]]
name = "twitter"
#url = "https://twitter.com/GoHugoIO"

[menu]
[[menu.main]]
    name = 'Home'
    pageRef = '/'
    weight = 1
[[menu.main]]
    name = 'About'
    pageRef = '/about'
    weight = 2
[[menu.main]]
    name = 'Calendar'
    pageRef = '/calendar'
    weight = 3
[[menu.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 4
[[menu.main]]
    name = 'Dens'
    identifier = 'dens'
    pageRef = '/dens'
    weight = 5
[[menu.main]]
    name = 'Activities'
    identifier = 'activities'
    pageRef = '/activities'
    weight = 6
[[menu.main]]
    name = 'Registration'
    pageRef = '/register'
    weight = 7


